import 'dotenv/config';
import express from 'express';import mongoose from 'mongoose';import cors from 'cors';import helmet from 'helmet';import morgan from 'morgan';import rateLimit from 'express-rate-limit';import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';
import {User,Bus,Route,Location,Complaint} from './models.js';import {protect,adminOnly,notFound,errorHandler} from './middleware.js';
const app=express(),PORT=process.env.PORT||5000;
if(!process.env.JWT_SECRET||process.env.JWT_SECRET.length<32){console.error('JWT_SECRET must be at least 32 characters.');process.exit(1);}
app.use(helmet());app.use(cors({origin:(process.env.CLIENT_ORIGIN||'http://localhost:5173').split(',')}));app.use(express.json({limit:'1mb'}));app.use(morgan('dev'));app.use('/api/auth',rateLimit({windowMs:900000,limit:30,standardHeaders:true,legacyHeaders:false}));
app.get('/api/health',(req,res)=>res.json({status:'ok',service:'transport-portal'}));
const tokenFor=u=>jwt.sign({id:u._id},process.env.JWT_SECRET,{expiresIn:'7d'}),publicUser=u=>({id:u._id,name:u.name,email:u.email,role:u.role});
app.post('/api/auth/register',async(req,res,next)=>{try{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8)return res.status(400).json({message:'Enter a valid name/email and password with at least 8 characters.'});const user=await User.create({name,email,passwordHash:await bcrypt.hash(password,12)});res.status(201).json({token:tokenFor(user),user:publicUser(user)});}catch(e){next(e);}});
app.post('/api/auth/login',async(req,res,next)=>{try{const u=await User.findOne({email:String(req.body.email||'').trim().toLowerCase()}).select('+passwordHash');if(!u||!(await bcrypt.compare(String(req.body.password||''),u.passwordHash)))return res.status(401).json({message:'Email or password is incorrect.'});res.json({token:tokenFor(u),user:publicUser(u)});}catch(e){next(e);}});
app.get('/api/auth/me',protect,(req,res)=>res.json({user:publicUser(req.user)}));
function resources(path,Model){app.get('/api/'+path,protect,async(req,res,next)=>{try{res.json(await Model.find().sort({createdAt:-1}).limit(500));}catch(e){next(e);}});app.post('/api/'+path,protect,adminOnly,async(req,res,next)=>{try{res.status(201).json(await Model.create(req.body));}catch(e){next(e);}});app.patch('/api/'+path+'/:id',protect,adminOnly,async(req,res,next)=>{try{const x=await Model.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!x)return res.status(404).json({message:'Record not found.'});res.json(x);}catch(e){next(e);}});app.delete('/api/'+path+'/:id',protect,adminOnly,async(req,res,next)=>{try{const x=await Model.findByIdAndDelete(req.params.id);if(!x)return res.status(404).json({message:'Record not found.'});res.json({message:'Record deleted.'});}catch(e){next(e);}});}
resources('buses',Bus);resources('routes',Route);resources('locations',Location);
const populated=q=>q.populate('user','name email').populate('bus','busNumber').populate('route','routeNumber source destination').populate('location','name area');
app.get('/api/complaints',protect,async(req,res,next)=>{try{const f=req.user.role==='admin'?{}:{user:req.user._id};if(req.query.status)f.status=req.query.status;if(req.query.category)f.category=req.query.category;if(req.query.q){const q=String(req.query.q).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');f.$or=[{complaintId:new RegExp(q,'i')},{description:new RegExp(q,'i')}];}res.json(await populated(Complaint.find(f).sort({createdAt:-1}).limit(300)));}catch(e){next(e);}});
app.post('/api/complaints',protect,async(req,res,next)=>{try{const {category,description,bus,route,location,priority}=req.body;const c=await Complaint.create({user:req.user._id,category,description,bus:bus||null,route:route||null,location:location||null,priority:['Low','Medium','High'].includes(priority)?priority:'Medium',history:[{status:'Submitted',note:'Complaint submitted',updatedBy:req.user._id}]});res.status(201).json(await populated(Complaint.findById(c._id)));}catch(e){next(e);}});
app.get('/api/complaints/:id',protect,async(req,res,next)=>{try{const c=await populated(Complaint.findById(req.params.id));if(!c)return res.status(404).json({message:'Complaint not found.'});if(req.user.role!=='admin'&&String(c.user._id)!==String(req.user._id))return res.status(403).json({message:'You can only view your own complaints.'});res.json(c);}catch(e){next(e);}});
app.patch('/api/complaints/:id',protect,async(req,res,next)=>{try{const c=await Complaint.findById(req.params.id);if(!c)return res.status(404).json({message:'Complaint not found.'});if(req.user.role!=='admin'){if(String(c.user)!==String(req.user._id))return res.status(403).json({message:'You can only edit your own complaints.'});if(c.status!=='Submitted')return res.status(400).json({message:'Only submitted complaints can be edited.'});for(const k of ['category','description','bus','route','location','priority'])if(req.body[k]!==undefined)c[k]=req.body[k]||(['bus','route','location'].includes(k)?null:'');}else{if(req.body.status&&!['Submitted','Under Review','In Progress','Resolved','Rejected'].includes(req.body.status))return res.status(400).json({message:'Invalid status.'});if(req.body.status&&req.body.status!==c.status){c.status=req.body.status;c.history.push({status:c.status,note:String(req.body.adminNote||'').slice(0,1000),updatedBy:req.user._id});}if(req.body.adminNote!==undefined)c.adminNote=String(req.body.adminNote).slice(0,1000);if(['Low','Medium','High'].includes(req.body.priority))c.priority=req.body.priority;}await c.save();res.json(await populated(Complaint.findById(c._id)));}catch(e){next(e);}});
app.delete('/api/complaints/:id',protect,async(req,res,next)=>{try{const c=await Complaint.findById(req.params.id);if(!c)return res.status(404).json({message:'Complaint not found.'});if(req.user.role!=='admin'&&(String(c.user)!==String(req.user._id)||c.status!=='Submitted'))return res.status(403).json({message:'Only your submitted complaints can be deleted.'});await c.deleteOne();res.json({message:'Complaint deleted.'});}catch(e){next(e);}});
app.get('/api/dashboard/stats',protect,adminOnly,async(req,res,next)=>{try{const [total,open,resolved,buses,routes,users,byStatus]=await Promise.all([Complaint.countDocuments(),Complaint.countDocuments({status:{$nin:['Resolved','Rejected']}}),Complaint.countDocuments({status:'Resolved'}),Bus.countDocuments(),Route.countDocuments(),User.countDocuments(),Complaint.aggregate([{$group:{_id:'$status',count:{$sum:1}}}])]);res.json({total,open,resolved,buses,routes,users,byStatus});}catch(e){next(e);}});
app.use(notFound);app.use(errorHandler);
mongoose.connect(process.env.MONGO_URI||'mongodb://127.0.0.1:27017/transport_complaints').then(()=>app.listen(PORT,()=>console.log('API listening on '+PORT))).catch(e=>{console.error('MongoDB connection failed:',e.message);process.exit(1);});